#!/usr/bin/env python3
"""
WingWing PPL Textbook - Supabase Upload Script

Reads generated JSON files and upserts them into the Supabase
`textbook_content` table, matching the exact schema used by the app.

Schema:
  id           uuid (auto-generated by Supabase)
  title        text
  slug         text (unique)
  chapter      integer
  section      integer  (A=1, B=2, C=3, D=4, E=5)
  path         text     (public/content/{lang}/chapters/{folder}/{file}.md)
  content      text     (raw markdown, no YAML frontmatter)
  metadata     jsonb    ({unit_title, faa_sources, wingwing_unit, wingwing_chapter, estimated_read_time})
  created_at   timestamptz
  updated_at   timestamptz

Required .env variables:
  SUPABASE_URL           https://xxxx.supabase.co
  SUPABASE_SERVICE_KEY   your service role key (from Supabase > Settings > API)
"""

import json
import os
import re
import sys
from pathlib import Path
from dotenv import load_dotenv

# ── Config ────────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent

env_path = PROJECT_ROOT / ".env"
if not load_dotenv(env_path, override=True):
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

JSON_EN_DIR = PROJECT_ROOT / "output" / "json-en"
JSON_ES_DIR = PROJECT_ROOT / "output" / "json-es"

UNIT_LETTER_TO_INT = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5}

# ── Helpers ───────────────────────────────────────────────────────────────────
def slugify(text):
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return re.sub(r"-+", "-", text).strip("-")


def strip_frontmatter(markdown):
    """Remove YAML frontmatter block from markdown content."""
    if markdown.startswith("---"):
        end = markdown.find("---", 3)
        if end != -1:
            return markdown[end + 3:].lstrip("\n")
    return markdown


def json_to_row(json_path, language):
    """Convert a JSON unit file to a Supabase row dict."""
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    chapter_num  = data["chapter_num"]
    unit_letter  = data["unit_letter"].upper()
    unit_title   = data["unit_title"]
    chapter_folder = data["chapter_folder"]
    filename     = data["filename"]

    # Strip frontmatter from the full markdown content
    content = strip_frontmatter(data["content_markdown"])

    # Build path matching app convention
    path = f"public/content/{language}/chapters/{chapter_folder}/{filename}"

    # Metadata blob (matches existing rows exactly)
    metadata = {
        "unit_title":          unit_title,
        "faa_sources":         data.get("faa_sources", []),
        "wingwing_unit":       unit_letter,
        "wingwing_chapter":    chapter_num,
        "estimated_read_time": data.get("estimated_read_time", 0),
    }

    # Slug: use path-based slug to keep en/es distinct
    base_slug = slugify(unit_title)
    slug = base_slug if language == "en" else f"{base_slug}-es"

    return {
        "title":    unit_title,
        "slug":     slug,
        "chapter":  chapter_num,
        "section":  UNIT_LETTER_TO_INT.get(unit_letter, 1),
        "path":     path,
        "content":  content,
        "metadata": metadata,
    }


# ── Upload ────────────────────────────────────────────────────────────────────
def upload_all(dry_run=False, test_one=False):
    from supabase import create_client

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY")

    if not url or not key:
        print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in .env")
        sys.exit(1)

    supabase = create_client(url, key)

    rows = []
    for language, json_dir in [("en", JSON_EN_DIR), ("es", JSON_ES_DIR)]:
        for json_file in sorted(json_dir.glob("*.json")):
            row = json_to_row(json_file, language)
            rows.append(row)

    print(f"\n{'='*60}")
    print(f"WingWing PPL Textbook — Supabase Upload")
    print(f"{'='*60}")
    print(f"Total rows to upsert: {len(rows)}")
    if dry_run:
        print("DRY RUN — no data will be written\n")

    if test_one:
        rows = rows[:1]
        print(f"TEST MODE — uploading 1 row only\n")

    success = 0
    failed = 0

    for row in rows:
        label = f"[ch{row['chapter']} s{row['section']}] {row['title']} ({row['path'].split('/')[2]})"
        if dry_run:
            print(f"  DRY  {label}")
            print(f"       slug={row['slug']} | {len(row['content'])} chars")
            success += 1
            continue

        try:
            result = (
                supabase.table("textbook_content")
                .upsert(row, on_conflict="slug")
                .execute()
            )
            print(f"  ✓  {label}")
            success += 1
        except Exception as e:
            print(f"  ✗  {label} — {e}")
            failed += 1

    print(f"\n{'='*60}")
    print(f"Done — {success} succeeded, {failed} failed")
    print(f"{'='*60}\n")


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Preview rows without uploading")
    parser.add_argument("--test",    action="store_true", help="Upload only the first row as a test")
    args = parser.parse_args()

    upload_all(dry_run=args.dry_run, test_one=args.test)
